[package]
name = "dingdangdong"
version = "0.1.0"
edition = "2021"
authors = ["dooyou21 <cubeclock94@gmail.com>"]
license = "MIT"

[dependencies]   
cpal = "0.15.2"
device_query = "1.1.3"
anyhow = "1.0.75"
ringbuf = "0.4.8"
